tlaplus/Examples

LICENSE.md
specifications/tower_of_hanoi/Bits.java
specifications/tower_of_hanoi/Bits.tla
specifications/tower_of_hanoi/Hanoi.tla
specifications/tower_of_hanoi/README.md

Make sure early on that users can freely copy and paste from the examples.

Add MIT license for Examples repository and "Tower of Hanoi" example specification

---

specifications/bcastByz/bcastByz.tla

Dear all,
I am Thanh Hai Tran, a PhD student from TU Vienna. I would like to add a specification bcastByz for the asynchronous reliable broadcast algorithm (Fig. 7) from the paper 
- T. K. Srikanth, Sam Toueg. Simulating authenticated broadcasts to derive simple fault-tolerant algorithms. Distributed Computing 1987, Volume 2, Issue 2, pp 80-94
My spec bcastByz has a TLAPS proof for the property Unforgeability.
I am looking forward to your reply. Thank you very much.
Best regards,
Thanh Hai Tran

bcastByz: new spec with TLAPS proof for Unforgeability

---

specifications/DieHard/MCDieHarder.tla

Removed duplicated "write" in comment

Fix tiny typo

---

README.md

I'm writing a toy specification of paxos by using the inbox and outbox of each replica as its state. Actually I'm a new player of TLA+ and I'm not sure whether it is a good way.
Looking forward to your reply and thanks very much.

adding a new toy specification of paxos

---

specifications/ParalleRaft/README.md

ParallelRaft is a variation of the Raft consensus protocol proposed in [_PolarFS:An ultra-low latency and failure resilient distributed file system for shared storage cloud database_.](https://www.vldb.org/pvldb/vol11/p1849-cao.pdf) We proposed a new consensus protocol ParallelRaft-CE based on ParallelRaft. We provided the formal specifications for ParallelRaft and  ParallelRaft-CE and  verified the refinement from ParallelRaft to Multi-Paxos and the correctness of ParallelRaft-CE.

Upload TLA+ specifications for ParallelRaft

---

specifications/DiningPhilosophers/DiningPhilosophers.cfg
specifications/DiningPhilosophers/DiningPhilosophers.tla

I've been trying to learn TLA+ to suss out a rare bug in my code. On https://learntla.com/temporal-logic/operators/ , I came across a toy Dining Philosophers problem. It took me several hours to make everything work and build something free of deadlocks, livelocks, or starvation, so I'd like to add my knowledge to the bank.
This model solves the problem via Dijkstra's [resource hierarchy solution](https://en.wikipedia.org/wiki/Dining_philosophers_problem#Resource_hierarchy_solution). You should be able to run it with no changes via VSCode or the command-line, or with minimal changes via TLA toolbox.

Add Dining Philosophers example

---

README.md

https://github.com/Alexander-N/tla-specs/issues/1

Add CRDT-Bug and asyncio-lock examples

---

specifications/README
specifications/glowingRaccoon/clean.tla
specifications/glowingRaccoon/product.tla
specifications/glowingRaccoon/stages.tla

this is mainly an excuse to use refinement mapping - the spec could be much better in terms of chemistry and biology
happy to make any needed changes!

adding PCR spec

---

README.md

Also added pluscal checkmark to Slush protocol

Fixed directory links in README

---

specifications/lamport_mutex/LamportMutex_proofs.tla

The title says it: fixing broken proofs in specifications/lamport_mutex.

fixed proofs of LamportMutex spec

---

.github/scripts/check_manifest_features.py
.github/scripts/check_manifest_files.py
.github/scripts/check_manifest_schema.py
.github/scripts/check_small_models.py
.github/scripts/generate_manifest.py
.github/scripts/parse_modules.py
.github/scripts/smoke_test_large_models.py
.github/scripts/tla_utils.py
.github/workflows/CI.yml
manifest.json

Script dependencies are all downloaded to separate paths to ensure all implicit dependencies are removed
Also parameterized the other python scripts
Removed auto-alphabetical sorting of author names in manifest generation script
Ref #77

Fixed implicit dependency on location of community modules jar

---

.github/workflows/CI.yml

Related: https://github.com/tree-sitter/py-tree-sitter/issues/148

Print out tool version info in CI

---

specifications/KeyValueStore/KVsnap.tla
specifications/KeyValueStore/MCKVsnap.cfg
specifications/KeyValueStore/MCKVsnap.tla

also fixed the empty writeset issue

Improved the model by making ops log process local variable

---

specifications/SpecifyingSystems/Liveness/LiveInternalMemory.tla
specifications/SpecifyingSystems/Liveness/README

Changed all instances of "req" to "busy".
Fixes #101

Applied Specifying Systems errata fix to exercises

---

.devcontainer/install.sh

Install TLAUC in gitpod & codespaces

---

README.md
manifest.json
specifications/ewd998/EWD998PCal.cfg
specifications/ewd998/EWD998PCal.tla

@muenchnerkindl Vanilla PlusCal variant of EWD998.

PlusCal variant of EWD998.

---

.github/workflows/CI.yml

Don't skip file now that https://github.com/tlaplus/tlaplus/pull/909 is merged.

pcal.trans can now handle utf8

---

specifications/KeyValueStore/ClientCentric.tla

Sync up with https://github.com/cwi-swat/tla-ci/blob/master/ClientCentric.tla

Add DOI of paper where ClientCentric TLA+ specifications are documented

---

.github/scripts/check_manifest_features.py
.github/scripts/check_manifest_files.py
.github/scripts/check_small_models.py
.github/scripts/requirements.txt
.github/scripts/smoke_test_large_models.py
.github/scripts/tla_utils.py
.github/scripts/unicode_number_set_shim.py
manifest-schema.json

Also:
- Fix bug in manifest/filesystem concordance validation script
- Locked tree-sitter-tlaplus version
cc @lemmy
Facilitates #155

Add action composition feature flag

---

.github/scripts/translate_pluscal.py

Added --enable_assertions flag to pcal translate script

---

specifications/LearnProofs/FindHighest.tla

Fixing broken proof in LearnProofs/FindHighest

---

.github/scripts/linux-setup.sh
.github/workflows/CI.yml
specifications/LoopInvariance/BinarySearch.tla
specifications/byzpaxos/Consensus.tla

The proof should now work with tlapm 1.6.0. Also added / simplified the liveness proof for this spec.

fixed (and simplified) proof in byzpaxos/Consensus.tla

---

.github/scripts/record_model_state_space.py
.github/workflows/CI.yml

Since this script had become broken it seems wise to smoke-test it in the CI.
@lemmy what is the reason that the EWD998ChanTrace state space varies?

CI: smoke-test state space script
