specifications/transaction_commit/TCommit.tla

Predicate name in comment was different to one used in formula.

Fixed predicate name in comment.

---

specifications/TecentPaxos/README.md

PaxosStore is a storage system used in wechat. See [PaxosStore@VLDB2017](https://www.vldb.org/pvldb/vol10/p1730-lin.pdf) by Tencent.
We give the specification of the consensus algorithm in PaxosStore and model check the refinement mapping we establish.

add links to tla+ file: specification of the consensus algorithm in Tencent storage system PaxosStore

---

specifications/Paxos/Paxos.tla

I believe there is a typo in the line: `None == CHOOSE v : v \notin Ballot`. Theoretically, `CHOOSE v: v \notin Ballot` is allowed to return a value for `None` that belongs to `Values`, but is outside of `Ballot`. The value `None` is used together with values, not ballots. The undefined value for ballot is -1.

Fixing None in Paxos

---

specifications/aba-asyn-byz/aba_asyn_byz.tla

There was a mistake in the fairness condition. It implicitly included the actions of Byzantine processes, which practically forces the Byzantine processes to cooperate with the correct processes.
To verify that there was a mistake, you can modify the threshold `guardR2` from `2 * T + 1` to `T + 1`. This change breaks the protocol and the model checking should fail, but it will pass with the original specification due to a too strong fairness condition.

Fix liveness checking in ada-asyn-byz

---

specifications/bcastByz/bcastByz.tla

Similar to #39
There was a mistake in the fairness condition. It implicitly included the actions of Byzantine processes, which practically forces the Byzantine processes to cooperate with the correct processes.
To verify that there was a mistake, you can change the threshold in `UponAcceptNotSentBefore` and `UponAcceptSentBefore` from `N - T` to `N - 2*T`. This change breaks the protocol and the model checking should fail, but it will pass with the original specification due to a too strong fairness condition.

Fix liveness checking in bcastByz

---

specifications/bcastByz/bcastByz.tla

It follows the changes mentioned in #40. I added additional proof steps in theorems related to the inductive invariants TypeOK and  FCConstraints. The updated proofs were checked with TLAPS version 1.4.5.

Fixed proofs in bcastByz

---

README.md

Modeling [Petri nets](https://en.wikipedia.org/wiki/Petri_net) in TLA+. Specific configurations can be instantiated and checked if they are valid for conventional Petri net safety and liveness properties.
The repo: https://github.com/elh/petri-tlaplus
Been really enjoying learning TLA+ and would love to contribute!

add Petri Nets from elh/petri-tlaplus

---

specifications/Bakery-Boulangerie/Bakery.tla

One proof failed in Bakery.tla but works when given a longer timeout period.

fixed failed proof in Bakery-Boulangerie/Bakery.tla

---

specifications/Bakery-Boulangerie/Bakery.tla

Fixes one part of #67 : the failure on Bakery.tla.

increase timeout for Z3 for one hard-to-prove obligation

---

.github/scripts/check_small_models.py
.github/scripts/parse_modules.py
.github/scripts/smoke_test_large_models.py
.github/scripts/tla_utils.py
.github/workflows/CI.yml
README.md
manifest.json

No longer do these scripts rely on various things being present at undocumented paths; all dependencies (tla2tools.jar path, manifest.json path, etc.) are now exposed using command line parameters. The scripts can be run from any working directory. These scripts also don't have any python package dependencies (tree-sitter etc.) so will be easy to run from the tlaplus/tlaplus repo CI instead of run.sh.
Also added a trigger to run the CI on a repository dispatch event, for the nightly tlaplus build to trigger.
Small amount of work necessary on tlaplus/tlaplus side but this is sufficient to close #77

Parameterize parse/check python scripts for ease of use from other repos

---

specifications/aba-asyn-byz/aba_asyn_byz.tla

Following the discussion in https://github.com/tlaplus/Examples/issues/80 I discovered a bug in the encoding w.r.t handling of messages by faulty processes. If a process was to become faulty after having sent messages, its messages might be counted twice, while the original algorithm counts messages by distinct senders, that is, it counts senders rather than counting messages.
The proposed change is the minimal I could figure out to fix that. Processes can turn Byzantine only in an initial process state. @konnov, can you also please have a look?

Bug fix in aba_asyn_byz.tla

---

.github/workflows/CI.yml

I think the lesson here is don't try to use tar on windows. Should probably do a squash-merge because a lot of these commits were small changes trying to get the CI to pass.

Fix tar CI failure on windows

---

.github/scripts/check_small_models.py
.github/scripts/smoke_test_large_models.py
.github/scripts/tla_utils.py
.github/workflows/CI.yml
manifest.json

Closes https://github.com/tlaplus/Examples/issues/85

TLC: capture stderr, print captured output on hard timeout

---

.github/workflows/CI.yml

Github actions appears to run `set -e` by default, so the tlapm install failure will abort the script and ignore the retry logic around it. We counteract this by running `set +e` right before the tlapm install retry loop.

Configure TLAPM install to proceed if exiting with nonzero error code

---

specifications/EinsteinRiddle/Einstein.tla

As you can see it does not look as good as before. The string constants now all have the _OF_TYPE prefix. I'm not sure how to do better. @konnov any suggestion?

Find solution to Einstein's riddle with Apalache

---

README.md
manifest.json
specifications/MultiPaxos-SMR/MultiPaxos.tla
specifications/MultiPaxos-SMR/MultiPaxos_MC.cfg
specifications/MultiPaxos-SMR/MultiPaxos_MC.tla
specifications/MultiPaxos-SMR/MultiPaxos_MC_small.cfg
specifications/MultiPaxos-SMR/README.md

Adds a new MultiPaxos spec at `specifications/MultiPaxos-SMR`. This is a spec that very closely models how a practical state machine replication (SMR) system would implement MultiPaxos.
A more detailed description can be found in the added README in the spec folder.
Proper updates to both the repo README and the `manifest.json` have been made. I hope the CI runs as expected.

Add Practical SMR-system-style MultiPaxos Spec

---

specifications/ewd998/EWD998.tla

The number of counted messages at each node and the number of messages in transit is consistent.

Update comment in EWD998.tla

---

.devcontainer/install.sh

The `z` flag in the `tar` command in the `install.sh` script was on the wrong position. This caused the following error: `tar: z: Cannot open: No such file or directory`.
Making `f` the last flag before the filename and moving the `z` to the front fixes the issue.

Fix incorrect tar flag in install.sh of devcontainer

---

README.md
manifest.json
specifications/tcp/MCtcp.cfg
specifications/tcp/MCtcp.tla
specifications/tcp/tcp.tla

TCP according to RFC 9293.

---

.github/scripts/check_small_models.py

Previously only the TLC output was printed; this will ease efforts to reproduce failures

Print out TLC command on failure for ease of local reproducibility

---

.github/scripts/translate_pluscal.py
.github/workflows/CI.yml
specifications/DiningPhilosophers/DiningPhilosophers.tla
specifications/LoopInvariance/BinarySearch.tla
specifications/LoopInvariance/Quicksort.tla
specifications/LoopInvariance/SumSequence.tla
specifications/MisraReachability/ParReach.tla
specifications/MisraReachability/ParReachProofs.tla
specifications/MisraReachability/Reachable.tla
specifications/MisraReachability/ReachableProofs.tla
specifications/MultiPaxos-SMR/MultiPaxos.tla
specifications/N-Queens/QueensPluscal.tla
specifications/N-Queens/QueensPluscal.toolbox/FourQueens/QueensPluscal.tla
specifications/TLC/TLCMC.tla
specifications/TeachingConcurrency/Simple.tla
specifications/TeachingConcurrency/SimpleRegular.tla
specifications/dijkstra-mutex/DijkstraMutex.tla
specifications/dijkstra-mutex/DijkstraMutex.toolbox/LSpec-model/DijkstraMutex.tla
specifications/dijkstra-mutex/DijkstraMutex.toolbox/Safety-4-processors/DijkstraMutex.tla
specifications/echo/Echo.tla
specifications/ewd687a/EWD687aPlusCal.tla
specifications/transaction_commit/2PCwithBTM.tla

The CI will fail if there is invalid PlusCal syntax in any of the modules. Previously, SANY would only warn of this but would return a zero exit code (see https://github.com/tlaplus/tlaplus/issues/899).
Also update the PlusCal translations of a number of modules with trivial differences.

Test PlusCal translation in CI

---

.github/scripts/check_manifest_features.py
.github/scripts/generate_manifest.py
.github/scripts/linux-setup.sh
.github/scripts/requirements.txt
.github/scripts/tla_utils.py
.github/scripts/unicode_number_set_shim.py
.github/scripts/windows-setup.sh
.github/workflows/CI.yml
README.md

We now release a python package for tree-sitter-tlaplus along with prebuilt wheels for various system types. Use this package to simplify scripts and instructions for users trying to execute the manifest generation script. It should no longer be necessary to manually download & build tree-sitter-tlaplus.

Use prebuilt python package for tree-sitter-tlaplus

---

.github/scripts/check_manifest_features.py
.github/scripts/check_proofs.py
.github/scripts/check_small_models.py
.github/scripts/generate_manifest.py
.github/scripts/linux-setup.sh
.github/scripts/parse_modules.py
.github/scripts/smoke_test_large_models.py
.github/scripts/tla_utils.py
.github/scripts/translate_pluscal.py
.github/scripts/unicode_conversion.py
.github/scripts/unicode_number_set_shim.py
.github/scripts/windows-setup.sh
.github/workflows/CI.yml
.gitignore
README.md
manifest-schema.json
manifest.json
specifications/EinsteinRiddle/Einstein.tla

This adds Apalache to the CI along with support for using it to check models marked as using the symbolic model-checking mode. Since this requires an extra parameter to be added to a number of scripts, this is a breaking change.
@konnov as FYI

Add Apalache to CI

---

.github/scripts/check_manifest_features.py
.github/scripts/check_markdown_table.py
.github/scripts/tla_utils.py
.github/scripts/unicode_number_set_shim.py
.github/workflows/CI.yml

Now that https://github.com/tlaplus-community/tlauc/issues/11 is fixed this should work.
Also activated the symbolic model checkmark validation for the markdown table, which had mistakenly stayed commented out.

Parse all translated unicode specs

---

.github/scripts/check_manifest_features.py
.github/scripts/generate_manifest.py
.github/scripts/requirements.txt
.github/scripts/unicode_number_set_shim.py

Also pin version of tree-sitter package to avoid problems in future.

Fix Python scripts in response to breaking tree-sitter API change

---

README.md
manifest.json
specifications/braf/BufferedRandomAccessFile.cfg
specifications/braf/BufferedRandomAccessFile.tla
specifications/braf/README.md

In review, @lemmy suggested adding this spec to our examples: https://github.com/tlaplus/tlaplus/pull/907#discussion_r1569827552
I made two small changes:
1. Pull config out into a separate file
2. Reduce `MaxOffset` from 4 to 3 so it can be checked in <10s (er, on my 8-core laptop anyway)

Add BufferedRandomAccessFile spec

---

.github/workflows/CI.yml

As discussed here: https://github.com/tlaplus/tlaplus/pull/976#issuecomment-2200274945
We will run the PlusCal translator to ensure it doesn't crash on invalid syntax, but we discard the translation so as not to overwrite modifications people might have made to the generated PlusCal code.

Discard PlusCal translations in CI

---

.github/scripts/smoke_test_large_models.py
.github/scripts/tla_utils.py
.github/workflows/CI.yml

Print out TLC command line call in smoke testing script and decode TLC output as UTF-8 if necessary.
Ref #119

Use macOS runner, minor script debug output fixes

---

README.md
manifest.json
specifications/Disruptor/Disruptor_MPMC.cfg
specifications/Disruptor/Disruptor_MPMC.tla
specifications/Disruptor/Disruptor_MPMC_liveliness.cfg
specifications/Disruptor/Disruptor_SPMC.cfg
specifications/Disruptor/Disruptor_SPMC.tla
specifications/Disruptor/README.md
specifications/Disruptor/RingBuffer.tla

The `Disruptor` is a concurrency library originally developed and open sourced by LMAX Exchange for low latency communication via a ring buffer between producer and consumer threads.
This PR adds a spec of the Disruptor lib and verifies that data races do not occur.

Add spec of the Disruptor concurrency library.

---

manifest.json
specifications/Disruptor/Disruptor_MPMC.cfg
specifications/Disruptor/Disruptor_MPMC.tla
specifications/Disruptor/Disruptor_MPMC_liveliness.cfg
specifications/Disruptor/Disruptor_SPMC.cfg
specifications/Disruptor/Disruptor_SPMC.tla

- Add comment on 'Multicast' behaviour.
- Add ASSUME for MaxPublished constant.
- Add comment on the usage of the 'consumed' variable.
- Remove WF from write actions.
- Remove bounding of model happening in BeginWrite action. Use a State constraint instead. Use suggestion for liveliness property.
- (The last two items are not done yet for the MPMC spec - it's less straight forward to do because of the multiple producers behaviour.)

Add small improvements to the Disruptor spec.

---

.github/scripts/check_small_models.py
.github/scripts/parse_modules.py
.github/scripts/smoke_test_large_models.py
.github/scripts/tla_utils.py

Expose `--enable_assertions` flag

Don't use JVM assertions by default in scripts

---

.github/workflows/CI.yml
specifications/TeachingConcurrency/SimpleRegular.tla

The proof of TeachingConcurrency/SimpleRegular.tla should now work with tlapm 1.6.0.

Fix simple regular

---

specifications/LoopInvariance/BinarySearch.tla

Should now work with tlapm 1.6.0.

fixed proof of LoopInvariance/BinarySearch

---

.github/workflows/CI.yml

If you push changes to a PR before the current CI run is complete, it will be terminated in favor of the new CI run.

CI: terminate outdated CI runs

---

.github/scripts/record_model_state_space.py
CONTRIBUTING.md
DEVELOPING.md
README.md

Changes:
- Add notes to README.md about how to usefully query the manifest.json file for various features (I especially often use this for advanced model file features like ALIAS and such)
- Move contributing instructions from README.md to standalone CONTRIBUTING.md for greater detail; emphasize the possibility of using `.ciignore`
- Document all the CI scripts and how to run them in DEVELOPING.md, along with how to consume this repo in your own project
- Noticed the `record_model_state_space.py` script was broken so I fixed it

Docs: added CONTRIBUTING.md and DEVELOPING.md

---

manifest.json

Enacts formatting and ordering changes on manifest.json.
It's good to run this script once in a while, as the manifest accrues pecularities due to people manually adding specs; this enables future users to run the script to add their own specs without introducing irrelevant changes.

Re-generate manifest from script
